### ISSUE TITLE
Add RTChanger to the app list.

### ISSUE THREAD

**Issue by AlbertCoolGuy** [BrewShop/BrewShopCTR#3]
**Project Name**:
RTChanger

**Author/GitHub repo owner**:
Storm-Eagle20

**GitHub repo/Other**:
Storm-Eagle20/RTChanger

**Category (look at categories.json to see which number it falls in)**:
2

**If Other than GitHub, download URL**:
[ ]

**Comment by Multimegamander** [comment]
Added!
